export type Milestone = { year: number; icon: string; title: string; desc: string }
export type KeyWork = { title: string; year: number; type: string }
export type ComposerBio = {
  id: string; fullName: string; years: string; birthYear: number; deathYear: number | null
  genre: string; nationality: string; era: string; tagline: string
  intro: string; earlyLife: string; career: string; legacy: string
  milestones: Milestone[]; keyWorks: KeyWork[]; funFact: string; related: string[]
}

export const COMPOSER_BIOS: ComposerBio[] = [
  // ===== CLASSICAL =====
  {
    id: 'bach', fullName: 'Johann Sebastian Bach', years: '1685–1750', birthYear: 1685, deathYear: 1750,
    genre: 'Classical', nationality: 'German', era: 'Baroque',
    tagline: 'The father of Western music who wove mathematics and devotion into sound',
    intro: 'Johann Sebastian Bach is regarded as one of the greatest composers of all time. A master of counterpoint, harmony, and musical architecture, his works represent the pinnacle of the Baroque era.',
    earlyLife: 'Born in Eisenach in 1685 into a family of over 50 professional musicians. Orphaned by age 10, he was raised by his eldest brother. He walked 250 miles to hear the great organist Buxtehude play.',
    career: 'Served as Thomaskantor in Leipzig from 1723 until his death, composing a cantata for nearly every Sunday — over 200 in total. Produced the Mass in B minor, St. Matthew Passion, Well-Tempered Clavier, and Goldberg Variations.',
    legacy: 'His music was largely forgotten until Mendelssohn revived the St. Matthew Passion in 1829. Beethoven called him "the immortal god of harmony." Today considered the supreme genius of Western music.',
    milestones: [
      { year: 1685, icon: '👶', title: 'Born in Eisenach', desc: 'Into a family of 50+ musicians' },
      { year: 1695, icon: '😢', title: 'Orphaned at 10', desc: 'Both parents die; raised by brother' },
      { year: 1705, icon: '🚶', title: 'Walks 250 miles', desc: 'To hear Buxtehude play organ' },
      { year: 1717, icon: '🎼', title: 'Brandenburg Concertos', desc: 'Six concertos for the Margrave' },
      { year: 1722, icon: '🎹', title: 'Well-Tempered Clavier', desc: '24 preludes and fugues in all keys' },
      { year: 1723, icon: '⛪', title: 'Thomaskantor', desc: 'Takes Leipzig position for 27 years' },
      { year: 1727, icon: '✝️', title: 'St. Matthew Passion', desc: 'Greatest sacred work' },
      { year: 1741, icon: '🎹', title: 'Goldberg Variations', desc: 'Summit of keyboard music' },
      { year: 1750, icon: '🕯️', title: 'Death', desc: 'Dies after failed eye surgery' },
    ],
    keyWorks: [
      { title: 'Brandenburg Concertos', year: 1721, type: 'Concerto' },
      { title: 'Well-Tempered Clavier', year: 1722, type: 'Keyboard' },
      { title: 'St. Matthew Passion', year: 1727, type: 'Oratorio' },
      { title: 'Mass in B minor', year: 1749, type: 'Choral' },
      { title: 'Goldberg Variations', year: 1741, type: 'Keyboard' },
      { title: 'Cello Suites', year: 1720, type: 'Suite' },
      { title: 'Toccata and Fugue in D minor', year: 1708, type: 'Organ' },
    ],
    funFact: 'Bach had 20 children. Four became famous composers. In parts of Germany, "Bach" became a synonym for "musician."',
    related: ['handel', 'vivaldi', 'mozart'],
  },
  {
    id: 'mozart', fullName: 'Wolfgang Amadeus Mozart', years: '1756–1791', birthYear: 1756, deathYear: 1791,
    genre: 'Classical', nationality: 'Austrian', era: 'Classical Period',
    tagline: 'The divine genius who composed over 800 works in just 35 years',
    intro: 'A child prodigy who began composing at five, Mozart produced an astonishing body of work across every genre — symphonies, concertos, operas, chamber music — all marked by melodic beauty and emotional depth.',
    earlyLife: 'Born in Salzburg, showed extraordinary talent from age three. His father Leopold took him on European tours where the child prodigy astonished royal courts. By twelve, he had written his first opera.',
    career: 'Moved to Vienna in 1781 as a freelance composer. Composed The Marriage of Figaro, Don Giovanni, The Magic Flute, his final symphonies, piano concertos, and the unfinished Requiem.',
    legacy: 'Died at 35 leaving 800+ compositions. His music embodies the Classical ideal while hinting at Romanticism. Beethoven, Schubert, and countless others built upon his innovations.',
    milestones: [
      { year: 1756, icon: '👶', title: 'Born in Salzburg', desc: 'Son of Leopold Mozart' },
      { year: 1761, icon: '🎹', title: 'First composition at 5', desc: 'Andante in C' },
      { year: 1762, icon: '🏰', title: 'European tour', desc: 'Performs at royal courts across Europe' },
      { year: 1764, icon: '🎼', title: 'First symphony at 8', desc: 'Symphony No. 1 in E-flat' },
      { year: 1781, icon: '🏙️', title: 'Moves to Vienna', desc: 'Freelance composer career begins' },
      { year: 1786, icon: '🎭', title: 'Marriage of Figaro', desc: 'His most beloved opera' },
      { year: 1787, icon: '🎭', title: 'Don Giovanni', desc: 'The "opera of all operas"' },
      { year: 1788, icon: '🎼', title: 'Final symphonies', desc: 'Nos. 39, 40, 41 "Jupiter"' },
      { year: 1791, icon: '🎭', title: 'The Magic Flute', desc: 'Last opera, September premiere' },
      { year: 1791, icon: '🕯️', title: 'Death at 35', desc: 'Dies composing the Requiem' },
    ],
    keyWorks: [
      { title: 'The Marriage of Figaro', year: 1786, type: 'Opera' },
      { title: 'Don Giovanni', year: 1787, type: 'Opera' },
      { title: 'The Magic Flute', year: 1791, type: 'Opera' },
      { title: 'Symphony No. 40', year: 1788, type: 'Symphony' },
      { title: 'Requiem', year: 1791, type: 'Choral' },
      { title: 'Piano Concerto No. 21', year: 1785, type: 'Concerto' },
      { title: 'Eine kleine Nachtmusik', year: 1787, type: 'Serenade' },
    ],
    funFact: 'At 14, Mozart transcribed Allegri\'s Miserere — a Vatican secret — from memory after a single hearing.',
    related: ['haydn', 'beethoven', 'schubert'],
  },
  {
    id: 'beethoven', fullName: 'Ludwig van Beethoven', years: '1770–1827', birthYear: 1770, deathYear: 1827,
    genre: 'Classical', nationality: 'German', era: 'Classical → Romantic',
    tagline: 'The titan who conquered deafness to revolutionize music',
    intro: 'Beethoven bridged the Classical and Romantic periods, expanding every form with unprecedented emotional power. He composed many of his greatest works while profoundly deaf.',
    earlyLife: 'Born in Bonn in 1770. His father pushed him relentlessly hoping to create another Mozart. By 11 he was deputy court organist. Moved to Vienna in 1792 to study with Haydn.',
    career: 'His "Heroic" period produced the Eroica, Fifth Symphony, Emperor Concerto, and Fidelio. As hearing deteriorated, his music became more experimental. Late works include the Ninth Symphony and late string quartets.',
    legacy: 'An estimated 20,000 attended his funeral. He transformed the symphony from entertainment into profound expression. The Ninth\'s "Ode to Joy" became the Anthem of Europe.',
    milestones: [
      { year: 1770, icon: '👶', title: 'Born in Bonn', desc: 'Son of court musician Johann' },
      { year: 1787, icon: '✨', title: 'Meets Mozart', desc: 'Mozart says "Keep your eyes on him"' },
      { year: 1792, icon: '🏙️', title: 'Moves to Vienna', desc: 'Studies with Haydn' },
      { year: 1798, icon: '👂', title: 'Hearing loss begins', desc: 'The tragedy that defines his life' },
      { year: 1802, icon: '📝', title: 'Heiligenstadt Testament', desc: 'Resolves to live for his art' },
      { year: 1804, icon: '🎼', title: 'Eroica Symphony', desc: 'Retracts Napoleon dedication' },
      { year: 1808, icon: '🎵', title: 'Fifth Symphony', desc: 'Da-da-da-DUM' },
      { year: 1810, icon: '🎹', title: 'Für Elise', desc: 'Most recognizable piano piece' },
      { year: 1824, icon: '🎼', title: 'Ninth Symphony', desc: 'Premieres while completely deaf' },
      { year: 1827, icon: '🕯️', title: 'Death', desc: '20,000 attend funeral' },
    ],
    keyWorks: [
      { title: 'Symphony No. 5', year: 1808, type: 'Symphony' },
      { title: 'Symphony No. 9 "Choral"', year: 1824, type: 'Symphony' },
      { title: 'Moonlight Sonata', year: 1801, type: 'Piano' },
      { title: 'Piano Concerto No. 5 "Emperor"', year: 1811, type: 'Concerto' },
      { title: 'Für Elise', year: 1810, type: 'Piano' },
      { title: 'Fidelio', year: 1805, type: 'Opera' },
    ],
    funFact: 'At the Ninth Symphony premiere, Beethoven was so deaf a soloist had to turn him around to see the standing ovation.',
    related: ['mozart', 'brahms', 'schubert'],
  },
  {
    id: 'chopin', fullName: 'Frédéric Chopin', years: '1810–1849', birthYear: 1810, deathYear: 1849,
    genre: 'Classical', nationality: 'Polish', era: 'Romantic',
    tagline: 'The poet of the piano who turned the keyboard into a voice of the soul',
    intro: 'Chopin composed almost exclusively for solo piano, creating nocturnes, études, preludes, waltzes, mazurkas, and polonaises of unmatched poetic beauty and technical innovation.',
    earlyLife: 'Born near Warsaw in 1810. A child prodigy, he gave his first public concert at age 7 and published his first composition at 8. Studied at the Warsaw Conservatory.',
    career: 'Left Poland at 20, never to return. Settled in Paris where he became the most sought-after piano teacher. His relationship with writer George Sand lasted nine years. He composed 230 works, all featuring the piano.',
    legacy: 'Died of tuberculosis at 39. His music redefined what the piano could express. Liszt, Debussy, Rachmaninoff, and every pianist since has been influenced by his innovations.',
    milestones: [
      { year: 1810, icon: '👶', title: 'Born near Warsaw', desc: 'In the Duchy of Warsaw' },
      { year: 1817, icon: '🎹', title: 'First composition at 7', desc: 'Polonaise in G minor' },
      { year: 1818, icon: '🎤', title: 'First public concert', desc: 'Performs for Warsaw aristocracy' },
      { year: 1829, icon: '🌟', title: 'Vienna debut', desc: 'Critics call him a genius' },
      { year: 1831, icon: '🇫🇷', title: 'Arrives in Paris', desc: 'Never returns to Poland' },
      { year: 1836, icon: '❤️', title: 'Meets George Sand', desc: 'Beginning of famous relationship' },
      { year: 1838, icon: '🎹', title: '24 Preludes', desc: 'Composed in Majorca' },
      { year: 1849, icon: '🕯️', title: 'Death in Paris', desc: 'Dies of tuberculosis at 39' },
    ],
    keyWorks: [
      { title: 'Nocturnes', year: 1832, type: 'Piano' },
      { title: '24 Preludes', year: 1839, type: 'Piano' },
      { title: 'Ballade No. 1', year: 1835, type: 'Piano' },
      { title: 'Étude Op. 10 No. 3 "Tristesse"', year: 1832, type: 'Piano' },
      { title: 'Polonaise "Heroic"', year: 1842, type: 'Piano' },
      { title: 'Piano Sonata No. 2 "Funeral March"', year: 1839, type: 'Piano' },
    ],
    funFact: 'Chopin requested that his heart be removed after death and sent to Poland. It rests in a pillar of the Holy Cross Church in Warsaw to this day.',
    related: ['liszt', 'debussy', 'rachmaninoff'],
  },
  {
    id: 'vivaldi', fullName: 'Antonio Vivaldi', years: '1678–1741', birthYear: 1678, deathYear: 1741,
    genre: 'Classical', nationality: 'Italian', era: 'Baroque',
    tagline: 'The Red Priest who gave the world The Four Seasons',
    intro: 'Vivaldi was a virtuoso violinist and prolific composer who wrote over 500 concertos and 46 operas. The Four Seasons remains one of the most popular pieces of classical music worldwide.',
    earlyLife: 'Born in Venice in 1678. Ordained as a priest (his red hair earned him the nickname "Il Prete Rosso") but was excused from saying Mass due to chest ailments — likely asthma.',
    career: 'Spent most of his career at the Ospedale della Pietà, a girls\' orphanage in Venice, where he taught and composed. His concertos influenced Bach, who transcribed several of them.',
    legacy: 'Died in poverty in Vienna in 1741 and was largely forgotten for 200 years. Rediscovered in the 1920s, his music sparked a Baroque revival.',
    milestones: [
      { year: 1678, icon: '👶', title: 'Born in Venice', desc: 'Son of a barber and violinist' },
      { year: 1693, icon: '⛪', title: 'Enters seminary', desc: 'Begins training for priesthood' },
      { year: 1703, icon: '🎻', title: 'Joins Pietà', desc: 'Becomes violin teacher at famous orphanage' },
      { year: 1711, icon: '📖', title: 'L\'Estro Armonico', desc: 'Published concertos make him famous across Europe' },
      { year: 1725, icon: '🌿', title: 'The Four Seasons', desc: 'His most famous work published' },
      { year: 1741, icon: '🕯️', title: 'Death in Vienna', desc: 'Dies in poverty, buried in unmarked grave' },
    ],
    keyWorks: [
      { title: 'The Four Seasons', year: 1725, type: 'Concerto' },
      { title: 'Gloria in D major', year: 1715, type: 'Choral' },
      { title: 'L\'Estro Armonico', year: 1711, type: 'Concerto' },
      { title: 'Stabat Mater', year: 1712, type: 'Choral' },
    ],
    funFact: 'Bach so admired Vivaldi that he transcribed at least 10 of his concertos for other instruments. Without Vivaldi, Bach\'s music might sound very different.',
    related: ['bach', 'handel', 'telemann'],
  },
  {
    id: 'tchaikovsky', fullName: 'Pyotr Ilyich Tchaikovsky', years: '1840–1893', birthYear: 1840, deathYear: 1893,
    genre: 'Classical', nationality: 'Russian', era: 'Romantic',
    tagline: 'The master of melody who gave the world Swan Lake and The Nutcracker',
    intro: 'Tchaikovsky\'s music combines soaring melodies with brilliant orchestration and deep emotional expression. His ballets, symphonies, and concertos are among the most beloved in the repertoire.',
    earlyLife: 'Born in Votkinsk, Russia. Initially studied law but abandoned it for music at the St. Petersburg Conservatory, graduating in 1865.',
    career: 'Composed Swan Lake, Sleeping Beauty, and The Nutcracker — the three most performed ballets in history. Also wrote six symphonies, the 1812 Overture, and Piano Concerto No. 1.',
    legacy: 'Died in 1893. His music bridges Russian nationalism and Western European tradition. The Nutcracker alone generates more ticket revenue than any other ballet worldwide.',
    milestones: [
      { year: 1840, icon: '👶', title: 'Born in Votkinsk', desc: 'In the Ural region of Russia' },
      { year: 1862, icon: '🎼', title: 'Enters conservatory', desc: 'St. Petersburg Conservatory' },
      { year: 1875, icon: '🎹', title: 'Piano Concerto No. 1', desc: 'Initially rejected, becomes iconic' },
      { year: 1877, icon: '🩰', title: 'Swan Lake', desc: 'First ballet (initially a flop)' },
      { year: 1880, icon: '🎆', title: '1812 Overture', desc: 'Complete with cannon fire' },
      { year: 1888, icon: '🎼', title: 'Symphony No. 5', desc: 'Triumph after creative crisis' },
      { year: 1890, icon: '🩰', title: 'Sleeping Beauty', desc: 'His most lavish ballet' },
      { year: 1892, icon: '🩰', title: 'The Nutcracker', desc: 'Now the world\'s most performed ballet' },
      { year: 1893, icon: '🎼', title: 'Pathétique Symphony', desc: 'Premieres 9 days before death' },
      { year: 1893, icon: '🕯️', title: 'Death', desc: 'Dies in St. Petersburg at 53' },
    ],
    keyWorks: [
      { title: 'Swan Lake', year: 1877, type: 'Ballet' },
      { title: 'The Nutcracker', year: 1892, type: 'Ballet' },
      { title: 'Symphony No. 6 "Pathétique"', year: 1893, type: 'Symphony' },
      { title: 'Piano Concerto No. 1', year: 1875, type: 'Concerto' },
      { title: '1812 Overture', year: 1880, type: 'Orchestral' },
      { title: 'Violin Concerto', year: 1878, type: 'Concerto' },
    ],
    funFact: 'Tchaikovsky\'s 1812 Overture calls for actual cannons to be fired during the performance. Some outdoor performances still use real artillery.',
    related: ['brahms', 'dvorak', 'rachmaninoff'],
  },
  // ===== JAZZ =====
  {
    id: 'miles-davis', fullName: 'Miles Davis', years: '1926–1991', birthYear: 1926, deathYear: 1991,
    genre: 'Jazz', nationality: 'American', era: 'Modern Jazz',
    tagline: 'The prince of darkness who reinvented jazz five times over',
    intro: 'Miles Davis shaped the course of modern jazz across five decades, pioneering cool jazz, hard bop, modal jazz, and fusion. Kind of Blue is the best-selling jazz album of all time.',
    earlyLife: 'Born in Alton, Illinois to a middle-class family. His father was a dentist. Started playing trumpet at 13. Moved to New York at 18, ostensibly to study at Juilliard but really to find Charlie Parker.',
    career: 'Led legendary quintets and sextets. Kind of Blue (1959) pioneered modal jazz. In a Silent Way and Bitches Brew (1969-70) invented jazz fusion. Constantly reinvented his sound.',
    legacy: 'Died in 1991. Every phase of his career — cool, hard bop, modal, fusion, electric — became a movement. He influenced not just jazz but rock, hip-hop, and electronic music.',
    milestones: [
      { year: 1926, icon: '👶', title: 'Born in Illinois', desc: 'Son of a dentist' },
      { year: 1944, icon: '🗽', title: 'Moves to New York', desc: 'Finds Charlie Parker on 52nd Street' },
      { year: 1949, icon: '❄️', title: 'Birth of the Cool', desc: 'Invents cool jazz' },
      { year: 1959, icon: '💙', title: 'Kind of Blue', desc: 'Best-selling jazz album ever' },
      { year: 1964, icon: '🎺', title: 'Second Great Quintet', desc: 'With Shorter, Hancock, Carter, Williams' },
      { year: 1970, icon: '⚡', title: 'Bitches Brew', desc: 'Invents jazz fusion' },
      { year: 1991, icon: '🕯️', title: 'Death', desc: 'Dies in Santa Monica at 65' },
    ],
    keyWorks: [
      { title: 'Kind of Blue', year: 1959, type: 'Album' },
      { title: 'Bitches Brew', year: 1970, type: 'Album' },
      { title: 'Birth of the Cool', year: 1957, type: 'Album' },
      { title: 'Sketches of Spain', year: 1960, type: 'Album' },
      { title: 'In a Silent Way', year: 1969, type: 'Album' },
    ],
    funFact: 'Miles once told a White House dinner guest who asked what he did for a living: "I\'ve changed the course of music five or six times. What have you done?"',
    related: ['john-coltrane', 'charlie-parker', 'herbie-hancock'],
  },
  {
    id: 'john-coltrane', fullName: 'John Coltrane', years: '1926–1967', birthYear: 1926, deathYear: 1967,
    genre: 'Jazz', nationality: 'American', era: 'Modern Jazz',
    tagline: 'The spiritual seeker who turned the saxophone into a prayer',
    intro: 'Coltrane\'s technical mastery and spiritual searching pushed jazz into new territory. A Love Supreme is considered sacred in jazz. His "sheets of sound" technique influenced every saxophonist who followed.',
    earlyLife: 'Born in Hamlet, North Carolina. Both grandfathers were ministers. Lost his father, aunt, and grandparents all within a year at age 12. Took up saxophone in high school.',
    career: 'Played with Miles Davis and Thelonious Monk before leading his own groups. A Love Supreme (1964) fused jazz with spiritual devotion. His late work pushed into free jazz and Eastern-influenced improvisation.',
    legacy: 'Died of liver cancer at just 40. In his short career, he transformed jazz more profoundly than almost anyone except Louis Armstrong. A Love Supreme was entered into the Library of Congress.',
    milestones: [
      { year: 1926, icon: '👶', title: 'Born in North Carolina', desc: 'Into a family of ministers' },
      { year: 1943, icon: '🎷', title: 'Takes up saxophone', desc: 'In high school' },
      { year: 1955, icon: '🎺', title: 'Joins Miles Davis', desc: 'First Great Quintet' },
      { year: 1957, icon: '🎹', title: 'Plays with Monk', desc: 'At the Five Spot Café' },
      { year: 1960, icon: '🎷', title: 'Giant Steps', desc: 'Revolutionary harmonic complexity' },
      { year: 1964, icon: '🙏', title: 'A Love Supreme', desc: 'Spiritual masterpiece' },
      { year: 1967, icon: '🕯️', title: 'Death at 40', desc: 'Liver cancer' },
    ],
    keyWorks: [
      { title: 'A Love Supreme', year: 1964, type: 'Album' },
      { title: 'Giant Steps', year: 1960, type: 'Album' },
      { title: 'Blue Train', year: 1958, type: 'Album' },
      { title: 'My Favorite Things', year: 1961, type: 'Album' },
    ],
    funFact: 'Coltrane practiced so obsessively he would fall asleep with the saxophone still in his mouth. He once said, "I want to be a saint."',
    related: ['miles-davis', 'thelonious-monk', 'charlie-parker'],
  },
  // ===== BLUES =====
  {
    id: 'robert-johnson', fullName: 'Robert Johnson', years: '1911–1938', birthYear: 1911, deathYear: 1938,
    genre: 'Blues', nationality: 'American', era: 'Delta Blues',
    tagline: 'The king of the Delta Blues who sold his soul at the crossroads',
    intro: 'Robert Johnson recorded only 29 songs in his short life, but they became the foundation of modern blues and rock. His legend — selling his soul to the devil at a crossroads — is music\'s greatest myth.',
    earlyLife: 'Born in Hazlehurst, Mississippi. Grew up in the Delta, fascinated by the blues musicians he heard at juke joints. Initially a mediocre guitarist, he disappeared for months and returned playing astonishingly well.',
    career: 'Recorded 29 songs in two sessions in 1936 and 1937, in San Antonio and Dallas. Cross Road Blues, Hellhound on My Trail, and Sweet Home Chicago became American standards.',
    legacy: 'Died at 27 under mysterious circumstances — likely poisoned. His recordings weren\'t widely heard until the 1960s, when they influenced the Rolling Stones, Eric Clapton, and Led Zeppelin. Keith Richards said: "He was like a comet that came and went."',
    milestones: [
      { year: 1911, icon: '👶', title: 'Born in Mississippi', desc: 'In the Delta region' },
      { year: 1929, icon: '🎸', title: 'Learns guitar', desc: 'Initially considered mediocre' },
      { year: 1931, icon: '😈', title: 'The crossroads legend', desc: 'Disappears, returns transformed' },
      { year: 1936, icon: '🎙️', title: 'First recording session', desc: '16 songs in San Antonio' },
      { year: 1937, icon: '🎙️', title: 'Second session', desc: '13 more songs in Dallas' },
      { year: 1938, icon: '🕯️', title: 'Death at 27', desc: 'Poisoned at a juke joint' },
    ],
    keyWorks: [
      { title: 'Cross Road Blues', year: 1936, type: 'Song' },
      { title: 'Hellhound on My Trail', year: 1937, type: 'Song' },
      { title: 'Sweet Home Chicago', year: 1936, type: 'Song' },
      { title: 'Love in Vain', year: 1937, type: 'Song' },
      { title: 'Come On in My Kitchen', year: 1936, type: 'Song' },
    ],
    funFact: 'Only two photographs of Robert Johnson are known to exist. His complete recordings fit on a single CD — yet they changed the course of popular music.',
    related: ['muddy-waters', 'bb-king', 'son-house'],
  },
  {
    id: 'bb-king', fullName: 'B.B. King', years: '1925–2015', birthYear: 1925, deathYear: 2015,
    genre: 'Blues', nationality: 'American', era: 'Electric Blues',
    tagline: 'The King of the Blues and his beloved guitar Lucille',
    intro: 'For over 50 years, B.B. King\'s expressive guitar playing and warm vocals defined modern blues. His guitar "Lucille" and his signature vibrato became the sound of the blues worldwide.',
    earlyLife: 'Born Riley B. King on a cotton plantation in Mississippi. Sang gospel in church as a boy. Moved to Memphis in 1948 where he got a radio job and the name "Blues Boy," shortened to B.B.',
    career: 'Recorded The Thrill Is Gone in 1969, his biggest hit. Toured relentlessly — over 300 shows a year for decades. Influenced every blues and rock guitarist who followed.',
    legacy: 'Played 15,000+ concerts over his career. Won 15 Grammy Awards. The Thrill Is Gone became the most recognizable blues song in the world. Died in Las Vegas at 89.',
    milestones: [
      { year: 1925, icon: '👶', title: 'Born in Mississippi', desc: 'On a cotton plantation' },
      { year: 1948, icon: '📻', title: 'Memphis radio', desc: 'Gets radio job, earns "Blues Boy" name' },
      { year: 1949, icon: '🎸', title: 'Names guitar Lucille', desc: 'After a fire caused by fighting men' },
      { year: 1951, icon: '🎵', title: 'First hit', desc: '"3 O\'Clock Blues" reaches #1 R&B' },
      { year: 1969, icon: '🏆', title: 'The Thrill Is Gone', desc: 'Biggest hit, defines his career' },
      { year: 2015, icon: '🕯️', title: 'Death at 89', desc: 'Dies in Las Vegas' },
    ],
    keyWorks: [
      { title: 'The Thrill Is Gone', year: 1969, type: 'Song' },
      { title: 'Live at the Regal', year: 1965, type: 'Album' },
      { title: 'Every Day I Have the Blues', year: 1955, type: 'Song' },
      { title: '3 O\'Clock Blues', year: 1951, type: 'Song' },
    ],
    funFact: 'B.B. King named every one of his guitars "Lucille" after a 1949 incident where two men fighting over a woman named Lucille knocked over a kerosene heater, setting the venue on fire. King ran back into the burning building to save his guitar.',
    related: ['robert-johnson', 'muddy-waters', 'albert-king'],
  },
]
